export enum textTypes {
    TITLE_BOLD = 'TITLE_BOLD', // 24px
    TITLE_REGULAR = 'TITLE_REGULAR',
    TITLE_LIGHT = 'TITLE_LIGHT',
    TITLE_THIN = 'TITLE_THIN',
    TITLE_SEMIBOLD = 'TITLE_SEMIBOLD',
    PARAG_BOLD = 'PARAG_BOLD',// 14px
    PARAG_REGULAR = 'PARAG_REGULAR',
    PARAG_LIGHT = 'PARAG_LIGHT',
    PARAG_THIN = 'PARAG_THIN',
    PARAG_SEMIBOLD = 'PARAG_SEMIBOLD',
    SUB_TITLE_BOLD = 'SUB_TITLE_BOLD',// 20px
    SUB_TITLE_REGULAR = 'SUB_TITLE_REGULAR',
    SUB_TITLE_LIGHT = 'SUB_TITLE_LIGHT',
    SUB_TITLE_THIN = 'SUB_TITLE_THIN',
    SUB_TITLE_SEMIBOLD = 'SUB_TITLE_SEMIBOLD',
    PARAG_SMALL_BOLD = 'PARAG_SMALL_BOLD',// 10px
    PARAG_SMALL_REGULAR = 'PARAG_SMALL_REGULAR',
    PARAG_SMALL_LIGHT = 'PARAG_SMALL_LIGHT',
    PARAG_SMALL_THIN = 'PARAG_SMALL_THIN',
    PARAG_SMALL_SEMIBOLD = 'PARAG_SMALL_SEMIBOLD',
    BUTTON_BOLD = 'BUTTON_BOLD',// 18px
    BUTTON_REGULAR = 'BUTTON_REGULAR',
    BUTTON_LIGHT = 'BUTTON_LIGHT',
    BUTTON_THIN = 'BUTTON_THIN',
    BUTTON_SEMIBOLD = 'BUTTON_SEMIBOLD',
}